canonical/netplan.io

- design.md
Adds curtin yaml link
fixes #27
> updated link in design

- examples.md
Add in an additional bond example received from Mark
Used ./run to view and preview site
None
None
> Additional bonding example

- faq.md
Add an actual example of using networkd-dispatcher
Used ./run to view during dev
> Add example using networkd-dispatcher

- faq.md
Add FAQ question for debugging
Used ./run to verify
> Add debug, troubleshooting FAQ question

- examples.md
Tighten up the language in a number of the examples.
> Proofreading

- faq.md
> Remove stray apostrophe

- examples.md
Add multi-address multi-gateway example.
> Add multi-address multi-gateway example

- _includes/head.html
- _layouts/default.html
> Update GTM code

- faq.md
> Fix 'netword' typo

- examples.md
https://github.com/canonical-websites/netplan.io/issues/48
> Make the bridging example fully stand-alone.

- _includes/footer.html
- _sass/_patterns_navigation.scss
- _sass/main.scss
- design.md
- examples.md
- faq.md
- package.json
- reference.md
- troubleshooting.md
- yarn.lock
Upgraded to Vanilla 1.8
- Fixed the spacing with H1s on pages with narrow strips at the top
- Styled the navigation logo text
- ./run
- Check the site in-browser - http://0.0.0.0:8024/
- See that it looks the same as (or better than) live
> 1.8 update

- examples.md
- reference.md
Update for new netplan features and documentation updates
Verified that the doc shows up correctly, same thing for the examples.
> Update for new netplan features and documentation updates

- package.json
- yarn.lock
- upgrades postcss-cli
- removes css-nano
Make sure ./run still works
> Remove css nano

- index.html
Changed link on index.html
Click it. Notice no notice :)
Fixes #61
> Fix link to NetworkManager

- faq.md
Let's add some additional context to the FAQ section regarding reverting back to ifupdown. I think this should be sufficient.
Fixes #75
> Rephrase the revert-to-ifupdown FAQ section, adding additional info

- .dockerignore
- Dockerfile
- nginx.conf
Multistage builds to decrease image size, faster image building.
- `export DOCKER_BUILDKIT=1`
- Build image with new dockerfile `docker build --tag myimage --build-arg BUILD_ID=myfakeid .`
- Run conainter with this image `docker run -ti -p 8111:80 myimage`
- Check build_id `myfakeid` is present `curl localhost:8111`
Fixes #77
> Multistage builds for netplan.io

- .github/workflows/tests.yml
Just removing a small space.
Make sure tests pass :)
> Remove space

- Gemfile.lock
- yarn.lock
Add not updated locks files
- `./run`
- http://0.0.0.0:8024/
- Works as usual
> Add locks files

- reference.md
Another update from the latest 0.99 doc changes. This can go in anytime! Thanks!
[List of work items including drive-bys]
> Update the reference page again with the latest doc updates.

- src/reference.md
Updated `src/reference.md` for netplan 0.100 release. (Copy & Paste from netplan source)
Execute `./run` and verify that the "References" page is not broken. (done)
> Update the reference page with the latest doc updates from netplan 0.100

- src/examples.md
Fix indentations I missed during the review.
Go to https://netplan-io-127.demos.haus/examples/ check examples indentations.
Fixes #125
> Fix examples indentation

- src/reference.md
Copy & Paste current reference.md from netplan git, updated for the 0.101 release.
> Update reference.md after Netplan 0.101 release

- src/reference.md
> reference.md : "scope: link" routes don't need "via"

- src/examples.md
Fix angle brackets in content
Check the code
Fixes https://github.com/canonical-web-and-design/netplan.io/issues/145
> Fix angle brackets in content

- src/design.md
Updated the "Commands" section of `design.md` to get in line with the commands available as of netplan v0.101
Executed ./run and checked visual output.
Fixes: #135 
> design: update Commands section

- src/reference.md
Updated `reference.md` according to netplan 0.102 upstream.
Spot check using `./run`
> Update reference.md after Netplan 0.102 release

- src/faq.md
Fix grammer and capitalisation on /faq
Go to http://0.0.0.0:8024/faq and see the improved sentence
Fixes #155
> Fix grammer and capitalisation on /faq

- src/examples.md
Fixed syntax of "Reaching a directly connected gateway" examples.
Fixes #153
> example: fix 'Reaching a directly connected gateway'

- src/examples.md
Fixed indentation in src/examples.md
Fixes #163 
> examples: fix routing/policy indentation

- Dockerfile
Changed dockerfile to use `node`, rather than `node-slim`
- See that the demo builds successfully
> Swap node-slim for node

- src/examples.md
- src/reference.md
Updated examples.md and reference.md according to netplan 0.102 upstream.
Visual check using `./run`
> Update examples and reference following the 0.103 release

- src/examples.md
Fix indentation of routes in vlan example
look at it
Fixing directly, no issue :D
> Fix indentation of routes in vlan example

- src/404.html
- src/500.html
- src/design.md
- src/faq.md
- src/index.html
- src/reference.md
- src/troubleshooting.md
- Vanilla fix on netplan.io to hide TOCs
Check the TOC's are hidden
> Add u-hide--small to TOC

- src/design.md
Check https://netplan-io-215.demos.haus/design/#complex-example
fixes https://github.com/canonical-web-and-design/netplan.io/issues/134
> Fix complex example indentation

- src/reference.md
Merge `reference.md` from upstream netplan v0.104: https://github.com/canonical/netplan/blob/main/doc/netplan.md
> Update reference for v0.104

- src/examples.md
examples: fix loopback YAML for adding an IP without clearing the existing loopback addresses
This issue was reported via IRC in #netplan
> examples: fix loopback YAML for adding an IP

- webapp/app.py
Update redirect for /examples
Check it fixes the 404 here: https://github.com/canonical/ubuntu.com/actions/runs/5177464655/jobs/9327589966
> Update redirect for /examples

- templates/index.html
* Clarify NetworkManager managing all interfaces via DHCP section
* Fixes https://github.com/canonical/netplan/pull/373
> index: clarify NetworkManager managing all interfaces via DHCP section

- .github/workflows/pr.yml
- package.json
- yarn.lock
Bumped cookie-policy to v3.6.4
- Delete cookies so you get the cookie policy pop up
- Accept nothing and check that in cookies there exists `_cookies_accepted=essential`
- Repeat with only accept 'performance', only accepting 'functional' and finally 'all'
[WD-13370](https://warthogs.atlassian.net/browse/WD-13370)
[WD-13370]: https://warthogs.atlassian.net/browse/WD-13370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WD-13370 Bumped cookie-policy to v3.6.4

- templates/base_layout.html
- Add GTM script to base layout
- Go to demo
- Check that Google Tag Manager is present in the HTML file
> Add Google Tag Manager script
