canonical/netplan.io

_includes/header.html
Our links should never contain `.html`.
But the `page.url` should match ".html" so the "selected page" shows up properly.
QA
--
``` bash
./run
```
Go to http://0.0.0.0:8024, click around the top nav. Check you never end up on a `.html` URL, and that the correct part of the navigation shows as active.
=> Show selected properly; dont add .html to links

README.md
i.e.: 8024
QA
--
Read the README. Check it correlates with the true `./run` experience.
=> Change README to mention correct port

Dockerfile, _layouts/default.html, nginx.conf
Fixes #3
QA
--
``` bash
./run build  # Build the site
docker build --build-arg COMMIT_ID=`git rev-parse HEAD` --tag netplan .  # Build the image
docker run -p 80:80 netplan  # Run the site container
```
Now visit http://localhost. Check the site works. Check also that redirects happen:
- http://localhost/index -> http://localhost
- http://localhost/index.html -> http://localhost
- http://localhost/documentation/ -> http://localhost/documentation
- http://localhost/documentation.html -> http://localhost/documentation
=> Add Dockerfile for building production containers

_includes/footer.html
Add help links -- specifically for AskUbuntu
Footer on all pages should list Netplan, Help, and Contribute columns.
=> Add help links on footer, based on maas.io.

examples.html
Just expanded the static ip example to include gateway and dns information.
- Open the examples page and check the rendering of the static ip example.
- create such a config and confirm that `netplan generate` and `netplan apply` produce the desired outcome: default route, dns search domains, dns ip.
Fixes #21
=> Expand the static example to include gateway and dns info

reference.md
The reference page is a clone of the man page. This is a sync of
the two pages to grab the latest changes and updates.
Fixes #33
Copy and paste from man page in netplan repo. From hash 1ab94ea56beab87f897ac1e4ddaeb9b4cc2667e5
Used ./run to demo page and verify page details
Fixes #33
=> Sync the reference page with the current man page

faq.md
The upstream project has changed its source repository from
github to gitlab; update url accordingly
Build the site, check the FAQ page, and ensure the networkd-dispatcher URL
points to https://gitlab.com/craftyguy/networkd-dispatcher
None
=> Update networkd-dispatcher repository url (github -> gitlab)

examples.md
Some users seem to have had a hard time to properly configure directly-connected gateways on ipv6 via netplan, as seen in the following askubuntu post:
https://askubuntu.com/questions/1148119/ipv6-default-route-not-being-set-netplan-ubuntu-18-04-2-lts
We have decided it would be best to include this particular example in the examples page (same change mirrored in the netplan examples/ directory).
=> Add example for a directly-connected gateway on IPv6.

.github/workflows/tests.yml
- Current Dockerfile is not building, merging multistage builds PR will fix this issue and it will allow github actions to build correctly.
- Github action to test run docker image
- Requires merging first multistage builds for this project. This action uses `DOCKER_BUILDKIT` therefore if it doesn't use it, it will fail to build the image.
=> Github action to run docker image

Dockerfile, renovate.json
Disable renovate to avoid upgrades to ruby 2.7.
=> Disable renovate for ruby

examples.md, reference.md
Let's not merge it just yet, but it's good to stage it. The reference section is a bit out of date.
Ideally I'd like to merge it when we backport 0.99 to all the stable series, as now it's only available in 20.04.
[List of work items including drive-bys]
=> Update the reference section, add an SR-IOV example

reference.md
Sadly, those two feature-flags didn't make it in time for 0.99. The *features* are there of course, but we don't have the flags for them in `netplan info`, which is unfortunate. So let's not confuse users. Since right now they might expect `netplan info` to report those - currently it won't, even though the features are available.
[List of work items including drive-bys]
=> Remove the 'requires feature' mentions for both modems: and SR-IOV

design.md
There is no such command as 'netplan config show' in the current
implementation of netplan. Deleting this section.
Executed `./run` and verified the section is gone from the "Design" page.
https://bugs.launchpad.net/netplan/+bug/1878631
=> design: Delete 'netplan config show' reference

reference.md
A lower metric has higher priority over a higher one.
- Corrected paragraph on DHCP overrides where it is stated that a higher metric would give an interface priority.
Fixes #102.
=> Correct documentation on dhcp overrides route-metric

index.html
Describe the `netplan try` command alongside `netplan generate` and `netplan apply`.
Executed `./run` and verified that the `netplan try` command is described in the "Commands" section on the frontpage.
=> Document the 'netplan try' command

src/reference.md
As applied in upstream github:
* Add note about gateway4/6 usage
* Fix formatting of Wireguard keys
Checked output/rendering of `./run`
https://askubuntu.com/questions/1287501/ubuntu-19-10-network-problem-with-public-ip-connects-but-cannot-send-anything/1287503#1287503
=> Update docs and fix Wireguard formatting

src/examples.md
- Use 4 spaces, rather than 2 in yaml on /examples
1. go to http://localhost:8024/examples/
2. see that yaml examples use four spaces
Fixes #125
=> Use 4 spaces in yaml on /examples

src/_includes/footer.html
Updated Github URL: Repository was moved to the "canonical" organization, from "CanonicalLtd".
https://github.com/canonical/netplan
=> Update Github URL

src/design.md
The YAML snippets in the design page had a stray backtick. Also, add the yaml
tag for the snippets, so that coloring works correctly.
=> Fix YAML snippets in the design page.

package.json, yarn.lock
[watch-cli](https://www.npmjs.com/package/watch-cli) is no longer maintained and has been forked and its deps updated as [watch-cli-only](https://www.npmjs.com/package/watch-cli-only). As [reported by the maintainer](https://github.com/doowb/watch-cli/issues/12).
- Pull this branch down
- Run `dotrun clean`
- Run `dotrun` as that will install the new package and use the watch npm scripts
- See there are no errors in the terminal
- Go to the site and check its working as expected
=> Switch to using the secure version of watch-cli

templates/faq.html
Improve pre/post-up/down dispatcher hooks documentation, according to specification FO0039.
Executed `./run` and did a visual inspection of the local FAQ website.
[FO0039](https://docs.google.com/document/d/1PaVchsKksmqs1ERnFATpAtk9eaIZeujtaTaYB-anx7Q)
N/A
=> templates:faq: update documentation on dispatcher hooks

templates/design.html
Fixed typo
Verify no stray \` in the netplan.yaml example for Subiquity
=> Fix typo in subiquity example

webapp/app.py
webapp: Fix reference/examples redirect, after dirhtml RTD configuration
The upstream documentation on ReadTheDocs (RTD), changed to use the dirhtml renderer: https://github.com/canonical/netplan/commit/2dad7d1
Checked redirect of https://netplan-io-269.demos.haus/reference#properties-for-device-type-ethernets
https://bugs.launchpad.net/netplan/+bug/2020228
=> Fix reference/examples redirect, after dirhtml docs configuration
